server:
  port: 8082

spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
  grpc:
    server:
      port: 9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/